version: '3.9'

services:
    equityiq-backend:
        build:
            context: .
            platforms:
                - 'linux/amd64'
        image: 730335200226.dkr.ecr.ap-south-1.amazonaws.com/equityiq/backend:latest
        restart: always
        ports:
            - '${PORT}:${PORT}'
        environment:
            NODE_ENV: ${NODE_ENV}
            LOG_LEVEL: ${LOG_LEVEL}
            NPM_AUTH_TOKEN: ${NPM_AUTH_TOKEN}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_REGION: ${AWS_REGION}
        env_file:
            - .env
